apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:qReYRWUWoGiG8U1xuacUmYfTAuxI1nBlnRnVefeYHEG6r7SatCemRdLGZAMaumx/h/1pvaxI6nqB5BS62VB2hHHSopuC3dFizrIlAntDuJhNXbhYC32fa7jWZIQ4vxvmRbJ0j39AAhWZvdHwaQYce+qW4LF7DSLwyULwk/evixUH0oY2IkaUyTs1UCsER+Dcqtdk1YOQaUhQ8oBWPPhE3nbQDEHu+kOpI8cMxH5TW4sJ6FLJJWd8cbZ1JNMGYU/TW8SGC6yOXxhggGo5Sc1NmgXbbmB+koumwxBPf5hTELb11vqrMBKh74T4fmY=,iv:/RDgTt1dBiIi3zD0JEpLpwz1ozS653YfnSLd+tIWnac=,tag:Qnr+556jpp3DQHLK6yrdFQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials-abs
sops:
    age:
        - recipient: age1jum4a6862hc9h6s3gwst2s8mctgjqs4ff6df0zhdwj2g8nam3sfsennvse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbnRDN0JacFc2ZnVpOHU2
            N3pLNUExenlEeGpoZy8xWm9FbHFrYmxsK1YwCnBTOTBWVVJQd0tiTlk3aVY0MUgw
            RmhUaUZpZHUwRlJkQ05pbzVHaHVVTFUKLS0tIHlsVEVoTkRiem8zUktyWWd1T0Q3
            SFVvQzRVWmJYbGN1TFdnc3BMZVl0SkUKnKT8KgSflY9mAsWDGi1uWH3VKHTyNijr
            j/TGpMTF1pL2MOcgX6lGa2AoVAA3Q6sLqCGVhCyxG1PdNpnrZdiV8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T20:05:36Z"
    mac: ENC[AES256_GCM,data:EEoJozUh7EL/BlU+Zo0PSmeR1RMRfTe1QFO85FxsEN2Gy4bBTWxhWXksyqwLCDtpt1PBaZBphSUfy6FoRwsm5/Rfdoctg47y5YJnDFed5aIRHAMqK1k1jWpaMlEh2bxldPp7WMSAHPGijLqnnYE8YTs9TrHn9DHUqCNMX6eQwUU=,iv:NOGW3L8T0gxC9DySmZUgbN2RQ83xyXgMgAwAh97gkGI=,tag:lADpZsOYHWKO0b1UNMECXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
