apiVersion: apps/v1
kind: Deployment
metadata:
  name: converternow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converternow
  template:
    metadata:
      labels:
        app: converternow
    spec:
      #securityContext:
      #  fsGroup: 33 # www-data group ID
      #  runAsUser: 33 # www-data user ID
      #  runAsGroup: 33 # www-data group ID

      containers:
        - name: converternow
          image: ghcr.io/ferraridamiano/converternow:v4.6.0
          ports:
            - containerPort: 8080


