apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      #securityContext:
      #  fsGroup: 1000 # node group ID
      #  runAsUser: 1000 # node user ID
      #  runAsGroup: 1000 # node group ID

      initContainers:
        - name: permissions-fix
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /audiobooks /podcasts /config /metadata"]
          volumeMounts:
            - mountPath: "/audiobooks"
              name: audiobooks-data

            - mountPath: "/podcasts"
              name: podcasts-data

            - mountPath: "/config"
              name: config-data

            - mountPath: "/metadata"
              name: metadata-data

      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.32.0
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap
          volumeMounts:
            - mountPath: "/audiobooks"
              name: audiobooks-data

            - mountPath: "/podcasts"
              name: podcasts-data

            - mountPath: "/config"
              name: config-data

            - mountPath: "/metadata"
              name: metadata-data

      volumes:
        - name: audiobooks-data
          persistentVolumeClaim:
            claimName: audiobooks-storage-pvc

        - name: config-data
          persistentVolumeClaim:
            claimName: config-storage-pvc

        - name: podcasts-data
          persistentVolumeClaim:
            claimName: podcasts-storage-pvc

        - name: metadata-data
          persistentVolumeClaim:
            claimName: metadata-storage-pvc


