apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:i1+VNAEiZx3zMQ6Nz7ut0Qb8R6GtZZITksN8pLt71PcabvFnV83koP2kjBUcCMjJIejWMTay/0FN7eLU8DqPuLFnBGv5Bw2RQAuBx2Pe0T6qjzhhVwVU2cT+Ld34kcKCuswQ3bOQNAVp1wkpCOIK0aZX/cv7xLGHEyov1xXdvPvSjxXOZVegkgh4LXIj2uOKXez3OWyPpOM5t0JWx5P+Ipw/lLx0YtHXrVqw2EGDp0sxkIf9YVjva3UCSpkIYzxHJ9zzCc9A00/UkUrma+5FXZxkf/cx4JEKGx9fnZgbR2i8JBx16BYh+Tunukk=,iv:lUmaybM/iGM3bFB8vMmnwNjx6Nm6e8tkEc6qx/G84Ks=,tag:eL8VfQgVfKQ85OCp+9cTfA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1jum4a6862hc9h6s3gwst2s8mctgjqs4ff6df0zhdwj2g8nam3sfsennvse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcmp2MlhKVnlqWDkrbU9l
            dG1UNHdyQ2x3dkZhOHlDTFFlL3AxTDBKQXdrCmJzbDlIS1R6UVNOM25kUnYyMjFu
            bkN5emdhejNIdHlnN1JVY0dNNUc0azgKLS0tIDB1dmtTWVZCb3pWc01oejkxRGE1
            T0JZWTZzVnc3akF1OXBHNUdqOHpnZFkKu7/epGFEBOe6dS14YhcuDddEPfLs1W4F
            OQQG93BjnPOdR3eRir2zhrt3VKzSY1NmXeds5QvM3+dxXeHs2vE8xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T20:13:03Z"
    mac: ENC[AES256_GCM,data:s/dYadMWIH88E3Q9NkrhfIUHaqLAGIa5T82aBPFNgVzEY3z6Z/iDjsglq5qKW0g/e/+VcoVUJaKe3Z+faXtoIDSr3XBJGLo738ChEnih+huta2trtYxfaOiEjetDVxJbe8W1Yq0ridmWaPJsHiHhj+sV5XWE+b/3FstTzA04wG4=,iv:kqaLj7FrptNXcZ/icelZ8RQ/Qv1MPW5/RUmOQg5nWlU=,tag:I9ntZWARCYIBNZCBuDhPvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
