apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:3dkkapHjJ2A=,iv:DhaFjqXHvH7Tkzn4rUGKytvaBAqTtlfID3hgdAwWwfs=,tag:QYQIAW3wHkWLHHX1V1WH2w==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:kc9RPRcRr7KX+qYF0Efyrar56jE=,iv:dvH084vP2g0PC9U1mSt32D81PKTT/negWEPRjtY3LfY=,tag:rBMNreoN/43SfTdHnBvHKw==,type:str]
kind: Secret
metadata:
    name: linkding-secret
sops:
    age:
        - recipient: age1jum4a6862hc9h6s3gwst2s8mctgjqs4ff6df0zhdwj2g8nam3sfsennvse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTTk2VnV5bTI4SWExS3Ni
            Q3ZPUjlSS3ZWR2R4bHhGTEJLSzZxYzQ4TUI4CjhwVXBjUXJOejQ0a2xzQ3FWNys2
            MDZNeU9Ib2xVMitqTkRrTjVoSUs5RmMKLS0tIGhxbHBrcWRvZTZUZk81R3dVM0lw
            YVZmMTZ1dU1aMkJpNmdQM2FranVvdzQKA24QL2SshzNhapLGyGxRQp/YUdZpHMeL
            rGwxzrnPofSRr6gYFc0y12wIgVhoNHXZyxDFL9WVNIS5qSvgIAMT8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T02:07:26Z"
    mac: ENC[AES256_GCM,data:MakBblN7zR5/O/r01zmCs+BRMM5rjZKwNDYlcp6bnMIb5u0WkVTBfdsLlX/kL7vetc30ifpoXP3LA067TTKcSb7Arebe0ft2z54TmoO5B2tNu48S+2cV1kB1D9SwKzKHzu4pazBfrbzGTlTJyfnCG+mXTrUluwNSeAoi1eaUc3g=,iv:i7iz6xcRs6NwSJ9gKqLICpirWe2YaGtdpy2Muf/5GFc=,tag:tZIzZDjfYFqeBdWhOGGu7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
