apiVersion: v1
data:
    password: ENC[AES256_GCM,data:jzZzceygpX/Wf+ny79bzbiW5GFc=,iv:JR1FDsCzSK8OA4MlS5f25nqP+ibuYaHPvJXSPL7mf9M=,tag:ExBeQ8HZ6DG5F0x75KETVA==,type:str]
    username: ENC[AES256_GCM,data:jEjgUZ+OWV4=,iv:vjdCDEZaWyJT5CiGPsvNfbPFEyy8hpuWuxUXxFUmvTQ=,tag:CEbenWxqvGB3GPnTPd+aKg==,type:str]
kind: Secret
metadata:
    name: linkding-secret
sops:
    age:
        - recipient: age1jum4a6862hc9h6s3gwst2s8mctgjqs4ff6df0zhdwj2g8nam3sfsennvse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVd3Ixb0dHOWt5Y1dCRlZl
            Rk5DRUUvc1ZXWDdtUjRra1JMTm9iV1FZZ3drCmxuNkt5Tk5ZSGEycGNqK0pXSERQ
            VkY4aXI0YUVSRnNBZDlKM1BvbjRSdGcKLS0tIFBZb3IwTTVMTlcyMExyT2R1N0tK
            TWl2SzNFMHkrbVR6ckVyYi9DOENuLzAKAmeCXEyFmAZDOQXumTMWv2isJM008Zg4
            EplNYc+94jv+739ZiaJJOwcSdTMRqKzfgZXZpl/847dqCZyAAXBHEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T20:28:24Z"
    mac: ENC[AES256_GCM,data:QcIX+IaTa1FiFqMk8oqBVTpEIUQKnXWfUbYowRiZXwoS6iLDzOuQRMYCJ6lgXVIoBW04A7uUMyRpx4wiGY2NriThR8ZW01EQMMhKFgyCLjmoNDI4SOXVP9JU/zG+ozPA86thSpleoighDxlNSwCXRtf3MGMpZSm0a9vz6To1jDc=,iv:I8++rbuIs81weRsAdNv3ucfTQhNg2kl4z/+HOYtudv0=,tag:hnq0nRvYxJEFQyGI6Y2R9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
