apiVersion: v1
data:
    password: ENC[AES256_GCM,data:HqUH2KZRXVQ=,iv:QkozRv8uVb5SjXE+5Cmjq86Xx10p9sN2TMBSG8rxSys=,tag:Kwk3seYDqc9tV9JG4e4Obw==,type:str]
    user: ENC[AES256_GCM,data:4h0vE3aRNgE=,iv:aYXFCcn86DroPBOBi0JlqlNl/NBfeEtz8SVRldXqnpA=,tag:G8rUbFrM1VfmcQsoBANhvA==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1jum4a6862hc9h6s3gwst2s8mctgjqs4ff6df0zhdwj2g8nam3sfsennvse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVWd2ZVBUazZOZUJBUTVz
            MnNVeUNBVjFsL2FBRlBZMVdXbGVOMThqMVhVCkg3eTZqUVMzRDRjUWNnSWhJL3Vj
            dlA4WG5QbG4zOWxSTVIwdTBKRnRoa3cKLS0tIHh4QjJlOXJuZlU2NWxrTm1nRE9J
            dDZFVW16d0RrN1dyVFhkZGsvWSt2MjgK8WOh3dRtiCUsOq98P1uA3zwA5/vC9Y1p
            B9nFHLp7umUPetdtKPuG77UJR4QpPBpfOlUKdrg2e7O/DUe5NxCIpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T19:35:05Z"
    mac: ENC[AES256_GCM,data:HUZh0LIFOuUEZx1Jk6gzVmn7qBkD5JQTAoDhwWROcK2qlZ9rx+Q/3EJ28QaurfrtYljYGpSMFj3hF1twGXgHErNT/yEmpGm7w2HzK7aqXBWHYdIgcHYa59hBRVmGzB4Pxy/btDcL0H8+90m/X690Muab3qVi+cheo51cDf3l3Wg=,iv:3WMCnid5eWkTjZYeB8EYHLsHn1vsMkWGGuRE4nPGv7g=,tag:zG/is1nnq7dlzEh2Z9eylw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
