apiVersion: v1
data:
    ops: ENC[AES256_GCM,data:5uhF4uylIcd+Nyenj6QfwQ==,iv:+FJvb/ZofZ13OVLBAx/s0P+Iju34MHBISkOuKWWX9ww=,tag:++9vL+Ormq3YxjPqGHFlOA==,type:str]
    whitelist: ENC[AES256_GCM,data:5nw3NCIS6C4d15A+N65R+g==,iv:zEfK8knMBQp1EgpOuw+ic8m8HrDUr3xyon5RXIoZm9M=,tag:U6th1pWJuqnxQExZE4hlcg==,type:str]
kind: Secret
metadata:
    name: minecraft-values
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSclJYZlk3MEprYVFQd0w3
            a1VGT0NlTEFMS2EycFp6QmlDT2RSYlpvdndFCkRzdGZBek45akNlREt2N0JCYmFo
            N1dBTWRGdExRYTZQZExOUFVXYkt5VEEKLS0tIGxxcktXMU8vM1RXOW16VkZTbmMy
            eG03L3J5dU5Pei85RXN0cWNzWnQ1dlUKPY4laXekoRFpUfxox89WNQa2qhcpV5Ok
            5xlFYaCWcw6yb+avpDLVcR+uV1chWsHqDHCm/P0HjELXhKugd1l8mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jum4a6862hc9h6s3gwst2s8mctgjqs4ff6df0zhdwj2g8nam3sfsennvse
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T21:39:20Z"
    mac: ENC[AES256_GCM,data:WMxp8ejskvqGC2mb02ms5l1PKjfLFaDM+HUDkrpuLNUmVLztTtNY1L0Kf/NAnnwCgQLWzIQoNhXps4MgfJJfT67+Fq7gNHX6C5SyJiRkIMR51N6ox1OIZTMaddKLlnay4tQpe9TMskSgVH1KGjPDp3ccZrHkwFgaQZpmB2cgZMM=,iv:rh36dOcHmyLutlmfUq9ymhqEovr/XrXMopYwNgLwnoY=,tag:ej2GyGCcjx2djDAxAt3pCA==,type:str]
    version: 3.13.3
