apiVersion: v1
data:
    SECRET_KEY: ENC[AES256_GCM,data:RbpfAz6FHxjBHE3lriOaAFWjwDhLj8mDD74eNWWeUFAZSnotPYKxS/Nrp3UXTtmcVaFi3pAgxvCpuam4xN+5G0M9P+QupGdOZp7kDaQcTF4MwtQV+sakhg==,iv:NWw+xFvdjMysLkCaYlV9pv31NvLOXe/skPehaGMu33E=,tag:sfSsowc5Xo3qpFwTfjJQ/w==,type:str]
kind: Secret
metadata:
    name: playit-agent-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNHNXWDBpekNNZ0RWSUIv
            ZXVnMUh4SGowZ3dTMDh0cWZjUnBKVFZXZFNBCmZqakRHUHhJZEZ2cDdpejZSQkI5
            SW5pcmRvay9NVmVTZnltWGtmUjgxWE0KLS0tIGRNMW5sam1HUnIxb09FOEp5TU5E
            elhvWkZXbllQZTZPMXh2NGFpNno4ZFUKsiwiAs3XrcIedEnPQgSqnWQEKxCLzEcT
            Tu+PoEK7EkiJWxysa4bT2bp0X2Z9vIR+gPIDilpuBenqeudfGuw69w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jum4a6862hc9h6s3gwst2s8mctgjqs4ff6df0zhdwj2g8nam3sfsennvse
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T23:08:39Z"
    mac: ENC[AES256_GCM,data:FoHIQQUezGpMq7PSEx5JIY3nAgkNOdtNI+gw5wtQo3wKtLBhajmPOq7JKA5B5VWPCz6d5AdJi/7BdMJjDEmzRuWzGRwnOgVOPiYVFfuE2kOvdGPSWwVSqYkNyAozYEohECqQ0W9xx+oDE1za0Ae0l5Ik9YoPgDo8Iotq9a9cNhA=,iv:2TmqOThA8PxXD9AAa4cDxwxGyV8+dvSSNoJx/XjBWRk=,tag:NjXtJWlqNs+qE3YTUjhKkw==,type:str]
    version: 3.13.1
