apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-stack
  namespace: minecraft
spec:
  interval: 10m
  chart:
    spec:
      chart: minecraft
      version: "*"
      sourceRef:
        kind:  HelmRepository
        name: itzg
        namespace: minecraft
      interval: 12h

  values:
    minecraftServer:
      eula: "TRUE"
      type: "PAPER"
      memory: 2048M
      serviceType: ClusterIP
      mode: creative

      whitelist: "tinyminey"
      ops: "tinyminey"

    persistence:
      dataDir:
        enabled: true
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        size: 10Gi
