apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:6SJRGuOKh/34SsZdWzd1aXz2F/hQLQAzZ5OhCuTgBZF7wfuQdy++Ajd/1BFoupRBwQCR9dX3W2k=,iv:LIYtaqVIXrlTkL275HWXiq4nqCbQo0DHqJenPtBVRXY=,tag:+n2SUrGIblWlDUK2abY0Sw==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age1jum4a6862hc9h6s3gwst2s8mctgjqs4ff6df0zhdwj2g8nam3sfsennvse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMmZUK1cxRVpoOGhJcVJQ
            WHkrQVRxWWhBRWpSWkFDSlBCRFBYMWN6d21NCm9ib0hsZW9aZU9GbngxbXlkeFk4
            TitsYWptKzF2N0dJdmhpZDU0em5XQU0KLS0tIDFYT2VzdTdjRmVIUnJ2YjcvZDJI
            QzQxbGtoUXg3QWhoZmlralJOZ3NxbWMKF7BD5LWjS2TSCNZV3cbaUCgCxGxmizGq
            BNQan2Y++Ze71iOov19AUPBKnQwh12JwEU+yZseC9UreRd7arqfPSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T20:25:19Z"
    mac: ENC[AES256_GCM,data:vRUarZvJb5b6hsTA7u0OruhJNNx2LtSVF5LWBL04SBhxKKqrr3TAhGZQAFTp4OdZNx8rWzY+UUyyiE6Z9ldfSEqeSkMtACVx+bL+hIoilywNhVTdzzZ+iQlarjmKxbl7XZSnRo/n+636NrDAAABnIm0F0ppuOJbHGvN6gXsrv0U=,iv:YyANtvdMjIInmLUvaptHfIfqiGvB6TgDzimGtnjyIuA=,tag:A8DQKnNGC7fUXbg0cHc9+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
